wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.title, name="title"),
    path("search_results/", views.search_results, name="search_results"),
    path("new_page/", views.new_page, name="new_page"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("save_changes/", views.save_changes, name="save_changes"),
    path("random_page/", views.random_page, name="random_page")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse
from . import util
import logging
import random
import markdown2
from markdown2 import Markdown

logger = logging.getLogger("encyclopedia.views")

class NewForm(forms.Form):
    search = forms.CharField(required= False,
    widget= forms.TextInput
    (attrs={'placeholder':'Title','style':'margin-bottom:2px;'}),
    label='')

class NewTextArea(forms.Form):
    title = forms.CharField(required= False,
    widget= forms.TextInput
    (attrs={'placeholder':'Title','class':'col-sm-8', 'style':'margin:2px;'}),
    label='')
    
    content = forms.CharField(
        widget=forms.Textarea
        (attrs={'class':'col-sm-8', 'style':'margin:2px; height: 50%;', 'placeholder':'Content'}),
    label='')

text_area= NewTextArea()
form = NewForm()


def index(request):
      
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form":form
    })

def new_page(request):

    if request.method == "POST":
        content_form = NewTextArea(request.POST)
        if content_form.is_valid():
            title = content_form.cleaned_data["title"].lower()
            content = content_form.cleaned_data["content"]

            all_topics = util.list_entries()
            all_topics = list(map(lambda x: x.lower(), all_topics))
            if title in all_topics:
                return render(request, "encyclopedia/error.html", {
                    "title": title,
                    "error": " already exist",
                    "form":form
                })
            else:
                util.save_entry(title,content)
                return render(request, "encyclopedia/title.html", {
                    "title": title,
                    "content": content,
                    "form":form
                })
        else:
            return render(request, "encyclopedia/new_page.html", {
                "text_area": text_area,
                "form":form
            })

    return render(request, "encyclopedia/new_page.html", {
        "text_area": text_area,
        "form": form
    })

def random_page(request):

    return title(request,random.choice(util.list_entries()))


def edit(request, title):
    if request.method == "GET":
        content = util.get_entry(title)
        pre_populated_form= NewTextArea(initial={'title': title, 'content': content})
        return render(request, "encyclopedia/edit.html", {  
            "pre_populated_form":pre_populated_form,
            "form": form 
        }) 



def save_changes(request):
    
    if request.method == "POST":
        content_form = NewTextArea(request.POST)
        if content_form.is_valid():
            title = content_form.cleaned_data["title"].lower()
            content = content_form.cleaned_data["content"]

            util.save_entry(title,content)
            content= markdown2.markdown(util.get_entry(title))  

            return render(request, "encyclopedia/title.html", {
                    "title": title,
                    "content": content,
                    "form":form
            })


def title(request,title):

    content= markdown2.markdown(util.get_entry(title))  

    if content is None:
        return render(request,"encyclopedia/not_found.html",{
        "title": title,
        "form":form
    })
    
    else:
        return render(request, "encyclopedia/title.html", {
        "title": title,
        "content": content,
        "form":form
    })

def search_results(request):

    if request.method == "GET":
        form = NewForm(request.GET)

        if form.is_valid():
            title = form.cleaned_data["search"].lower()
            content = util.get_entry(title)
            if content == None:
                similar_strings = []
                for string in util.list_entries():
                    if title in string:
                        similar_strings.append(string)
                 
                return render(request, "encyclopedia/not_found.html", {
                "title": title,
                "similar_topics": similar_strings,
                "form":form
                })
            else:
                return render(request, "encyclopedia/title.html", {
                    "title": title,
                    "content": content,
                    "form":form
                })

   

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{title}}
{% endblock %}


{% block body %}
<form action="{%  url 'wiki:save_changes'%}" method="post">
  <p><label >Add the Markdown content:</label></p>
  {% csrf_token %}
  {{pre_populated_form}}
  <br>
    <input type="submit" value="Save">
</form>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>{{title}}{{error}}</h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search_results' %}" method="get">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit", value="Search">
                </form>

                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
<h1>New Page</h1>

<form action="{% url 'wiki:new_page' %}" method="post">
  <p><label >Add the Markdown content:</label></p>
  {% csrf_token %}
  {{text_area}}
  <br>
    <input type="submit" value="Save">
</form>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>{{title}} is not found Opps</h1>
    <br>
    <h4>Similar Topics</h4>
    <ul>
    {% for topic in similar_topics %}
        <li><a href="{% url 'wiki:title' title=topic %}">{{topic}}</a></li>
    {% empty %}
        <li> No similar topics </li>

    {% endfor %}
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Pages</h1>

    <ul>
        <a href="{% url 'wiki:title' title=title %}">{{ title }}</a>
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content |safe }}
    <br> 
    <br> 
    <form action="{% url 'wiki:edit' title=title %}" method="get">
        {% csrf_token %}
        <!-- <input type="hidden" name="title" value="{{ title }}"> -->
        <button type="submit">Edit</button>
    </form>
{% endblock %}